spring:
  datasource:
    url: jdbc:h2:file:./testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    open-in-view: false
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

springdoc:
  swagger-ui:
    csrf:
      enabled: true


logging:
  level:
    root: DEBUG

hibernate:
  dialect: "org.hibernate.dialect.H2Dialect"

zielinskin:
  enable-scheduling: false
  cross-instance:
    external-instance-ip: null
    number-of-object-instances: 1000